Add package closer, adapted to be used with Zap logger.
CoreumFoundation/coreum-tools pull request #10
Opened 2022-06-06 13:52 UTC by xlab

Adding another package converted from external opensourced and bullet-proof version ([closer](https://github.com/xlab/closer), with changes to our Zap logging chain.

The package solves a simple problem: allows to quit app gracefully, with chain of cleanup functions.
The graceful exit shall be guaranteed for a list of system signals (like `SIGINT` etc), as well as any `panic`s reaching the `main` func.

**Usage pattern is like this:**

```go
func main() {
	defer closer.Close() // ensures we catch panics

	closer.Bind(func() {
		fmt.Println("I'm the cleanup chain! Step 2")
	})

	closer.Bind(func() {
		fmt.Println("I'm the cleanup chain! Step 1")
	})

	go doStuff()

	closer.Hold() // It just blocks until you press ^C etc
}
```

An example use case can be seen there:
https://github.com/CoreumFoundation/coreum/blob/c66f9630571bd7548a99030edfab3d2611dcae6e/coremon/cmd/coremon/cmd_process.go#L34-L40

The reason why I bringing this package there is because I don't want to have full IoC stuff dependency from znet just to handle graceful shutdowns upon signals, as can be seen there in `coreznet`:
https://github.com/CoreumFoundation/coreum-tools/blob/f8569e99fad668523fb29ffd200d7b890746e8c2/pkg/run/run.go#L72-L73
(which brings reflection, metaprogramming, goroutine manager parallel spawning, singletons and other IoC-related stuff on the plate for some reason)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)

2022-06-06 16:49 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3tuhiF-3s62DilFuAa:-N3tuhiF-3s62DilFuAb:b-thvjz4) (no related file):*
This entire thing has been already implemented: https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/run/run.go
If you have seen that implementation and you don't like sth there please come to me and we will fix once for all. But implementing everything from scratch because you don't like sth or don't know how to use it is really counter-productive because you must write it and I must review it.

___


<!-- Sent from Reviewable.io -->

2022-06-07 02:47 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3tuhiF-3s62DilFuAa:-N3w2jiq2aE7YZ1wHQ_q:b-5glk3e) (no related file):*
> you must write it

That's the most easiest part of the deal 🤣

___


<!-- Sent from Reviewable.io -->

2022-06-07 06:04 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3tuhiF-3s62DilFuAa:-N3wk2bRCnQnnKX5Fk0u:b-j0xjpa) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> you must write it

That's the most easiest part of the deal 🤣
</blockquote></details>

The deal is that you may do whatever you like as long as it's a temporary thing not going to reach the master. That's why I would recommend you to create another feature-master branch and target your PRs there, not to master. Otherwise I will actively block all of them until we eventually reach some agreement in the team on how apps are designed, because obviously we don't want to go in the direction where every dev uses different foundation for building apps.

___


<!-- Sent from Reviewable.io -->

2022-06-07 09:06 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3xOwRu3RwujGI9Pws3:-N3xPLaw5IsH76C6Nt0O:b-fv44d4) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What happends in `doStuff` if I press ctrl+C and `closer.Hold()` exits?
</blockquote></details>

Please provide more real-life example, where:
- goroutine is terminated gracefully after signal
- goroutine returns an error which should be propagated up the call stack

___


<!-- Sent from Reviewable.io -->

2022-06-07 09:07 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3xOwRu3RwujGI9Pws3:-N3xPiZv9WZXuQp-EBGL:b-pttjit) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please provide more real-life example, where:
- goroutine is terminated gracefully after signal
- goroutine returns an error which should be propagated up the call stack
</blockquote></details>

- and where panic inside goroutine is handled

___


<!-- Sent from Reviewable.io -->

2022-06-07 09:09 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3xOwRu3RwujGI9Pws3:-N3xQB5U5NU-yqsscHyi:b-3kharh) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

- and where panic inside goroutine is handled
</blockquote></details>

- and please add second goroutine to show how goroutines communicate with each other (simple sender-receiver is enough)

___


<!-- Sent from Reviewable.io -->

2022-06-07 09:11 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3xQPue-Yh7KXKkN8nd:-N3xQPue-Yh7KXKkN8ne:bmkdx3) (no related file):*
Please provide more real-life example, where:
- goroutine is terminated gracefully after signal
- goroutine returns an error which should be propagated up the call stack
- goroutine panics
- second goroutine to show how goroutines communicate with each other (simple sender-receiver is enough)

___


<!-- Sent from Reviewable.io -->

2022-06-07 20:30 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3xQPue-Yh7KXKkN8nd:-N3zr6qE-OXCaVXNvGlK:bvrv45u) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This package scope is limited to handle Ctrl+C signals and run a chain of callbacks when it arrives.
Discussion on goroutines management is out of scope totally.
</blockquote></details>

So please remove `// ensures we catch panics` from the example because it's not true

___


<!-- Sent from Reviewable.io -->

2022-06-08 07:06 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N3xQPue-Yh7KXKkN8nd:-N416kdrAkKUjmHiwhJT:b-u6jm5x) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So please remove `// ensures we catch panics` from the example because it's not true
</blockquote></details>

To give more context:
In your example the `main` function is responsible only for waiting for signal, doing some cleanup and starting goroutine(s).
This means that all the business logic is done in goroutines (because the main one is busy waiting for signal).
This means that 99.9% of the code is in goroutines.
This means that 99.9% of potential panics will come from goroutines.
This means that only 0.1% of panics will be handled by `defer closer.Close()`
This means that it is basically useless.

___


<!-- Sent from Reviewable.io -->

2022-06-08 07:11 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N418YGN6NqoFbFXeWuI:-N418YGN6NqoFbFXeWuJ:b1m6p6x) (no related file):*
Could you please explain the difference between

```
closer.Bind(func() {
	// do sth
})
```

and

```
defer func() {
	// do sth
}()
```

?

___


<!-- Sent from Reviewable.io -->

2022-06-09 10:19 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/10#-N46tP1r4BmKVjl3YSMY:-N46tP1r4BmKVjl3YSMZ:b-6l58kh) (no related file):*
I think I mentioned before that I believe that adding new packages / abstractions / architectural patterns or anything like that should be discussed in the team. Moreover I don't think that I consider closer package a battle tested package. 

___


<!-- Sent from Reviewable.io -->

2022-06-14 14:13 UTC, closed without merging