Add pace metering package
CoreumFoundation/coreum-tools pull request #8
Opened 2022-06-02 12:14 UTC by xlab

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)

2022-06-02 13:12 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3ZX9o95Bo7WVjbDdZS:-N3ZX9oABwXLQzzT4gqy:b-s6i7yt) (no related file):*
We need all this code (371 lines + unit tests) to just print the number of transactions per second executed concurrently?

___


<!-- Sent from Reviewable.io -->

2022-06-02 13:42 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3ZX9o95Bo7WVjbDdZS:-N3ZdM7x3_XscefHDq2j:b-vkj41r) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

1) the code was smaller before you asked to make use of atomic
2) the code wasn't there, instead, it was a small dependency included with 1 extra line.


So yea, now we need all that to print the number of transactions per second executed concurrently.

Also, what's the matter of saving disc space by shredding extra code lines? 
</blockquote></details>

It's not about disk space obviously, it's about understanding this and number of bugs which is proportional to the number of lines.
I'm very sure logic we need might be implemented in less than 50 lines, just in a function inside the `zstress` package in the main repo.

___


<!-- Sent from Reviewable.io -->

2022-06-02 13:43 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3ZX9o95Bo7WVjbDdZS:-N3ZdytCDvrWn3k8hK0Y:b-ejso1x) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not about disk space obviously, it's about understanding this and number of bugs which is proportional to the number of lines.
I'm very sure logic we need might be implemented in less than 50 lines, just in a function inside the `zstress` package in the main repo.
</blockquote></details>

Before even starting reviewing this I will wait for other guys opinion

___


<!-- Sent from Reviewable.io -->

2022-06-02 16:07 UTC, miladz68 reviewed
There are many functions and variables that we are not actively using in coreum. please remove those. for example 2 different types of reporters (log and zap), pause function. allowing float and int (we only need int). Also I prefer using atmic package instead of sync package. 

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-:-N3_9a95BZgkPeC0wADI:bhru6mr)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @xlab)



<!-- Sent from Reviewable.io -->

2022-06-02 16:08 UTC, miladz68 requested changes
I will block this for now.

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-:-N3_A4ry3tDwRcpe1CRQ:b-kp4ntg)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @xlab)



<!-- Sent from Reviewable.io -->

2022-06-02 17:12 UTC, wojtek-coreum reviewed
@miladz68 If you want to start a discussion in the PR, please use "Start a new discussion" button below. Here, in the main thread reviewable publishes info about commits and reviews so your comments might be lost in the history

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-:-N3_Og6F9qtBfuXJrMr7:b1qicw7)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @xlab)



<!-- Sent from Reviewable.io -->

2022-06-03 05:05 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3bwqVfEDfj4B91eqYg:-N3bwqVfEDfj4B91eqYh:b-h2akrs) (no related file):*
@xlab what are the things we are going to measure in `corezstress`? I know about transactions per second being broadcasted. Anything else?

___


<!-- Sent from Reviewable.io -->

2022-06-06 01:10 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3qV1624bCbqFwLBmM-:-N3qV1624bCbqFwLBmM0:bu8ig5d) (no related file):*
### Description of this package

Adding the description there in PR, so the git history is not covered with junk from README editing. If this PR is merged, a standalone README could be added for the future reference.

### Main idea

Pace is a Go package that helps to answer one simple question: _how fast it goes?_ It's a threadsafe counter that measures ticks in the specified timeframe. It also has a simple and intuitive interface:

```go
func New(label string, interval time.Duration, repFn ReporterFunc) Pace

type Pace interface {
    // Step increments the counter of pace.
    Step(n int)
    // Pause stops reporting until resumed, all steps continue to be counted.
    Pause()
}
```

Initially the package was a standalone external dependency, however for the project needs I was asked to include it into the source, so I've copied some (well-tested) code and also made modifications to ensure that the package doesn't provide extra functionality that we don't use. Package provides `ZapReporter` for  the only supported logger that we use.

### Usage examples

The package being used in a currently [pending PR](https://reviewable.io/reviews/CoreumFoundation/coreum/45#-) related to the `corezstress` utility. The utility itself is a CLI app, where without any logging the user doesn't get any idea what the app does at the moment. With a few additional lines of code that setups the pace instance, and ticking it once an event happens, logs will contain info about certain actions pacing (see output examples).

```go
signedTxPace := pace.New("signed tx", 10*time.Second, pace.ZapReporter(log))

			defer func() {
				signedTxPace.Pause()
			}()


					case result := <-results:
						signedTxPace.Step(1)

```

I think the package in this form served me well over years, to add some verbosity into random places in many tools and also as a debugging mechanism to detect stale flows (yes, the tool also reports whether the pacing becomes stale).

Important difference from the other reporting implementations like in [PR #44](https://reviewable.io/reviews/CoreumFoundation/coreum/44#-) is that with a standalone package user is abstracted away from implementing the counter every time with risk of adding concurrency-related and other possible bugs. Also, this drop-in makes code much easier to read.

### Output examples

```
INFO 329923 signed tx in 10s (pace: 32992.300/s)
INFO 333805 signed tx in 10s (pace: 33380.500/s)
INFO 333717 signed tx in 10s (pace: 33371.700/s)
INFO 333716 signed tx in 10s (pace: 33371.600/s)
INFO 334649 signed tx in 10s (pace: 33464.900/s)
INFO 334445 signed tx in 10s (pace: 33444.500/s)
INFO 336089 signed tx in 10s (pace: 33608.900/s)
INFO 333331 signed tx in 10s (pace: 33333.100/s)
INFO 329395 signed tx in 10s (pace: 32939.500/s)
```

```
INFO 3200 sent tx in 10s (pace: 320.000/s)
INFO 3600 sent tx in 10s (pace: 360.000/s)
INFO 3200 sent tx in 10s (pace: 320.000/s)
INFO 3428 sent tx in 10s (pace: 342.800/s)
INFO 2527 sent tx in 10s (pace: 252.700/s)
INFO 2145 sent tx in 10s (pace: 214.500/s)
INFO 2844 sent tx in 10s (pace: 284.400/s)
INFO 2432 sent tx in 10s (pace: 243.200/s)
```

___


<!-- Sent from Reviewable.io -->

2022-06-06 05:50 UTC, wojtek-coreum reviewed
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @xlab)



<!-- Sent from Reviewable.io -->

2022-06-06 08:37 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3qV1624bCbqFwLBmM-:-N3s8wJf6NJZCAutIbM6:boyauy7) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

### Description of this package

Adding the description there in PR, so the git history is not covered with junk from README editing. If this PR is merged, a standalone README could be added for the future reference.

### Main idea

Pace is a Go package that helps to answer one simple question: _how fast it goes?_ It's a threadsafe counter that measures ticks in the specified timeframe. It also has a simple and intuitive interface:

```go
func New(label string, interval time.Duration, repFn ReporterFunc) Pace

type Pace interface {
    // Step increments the counter of pace.
    Step(n int)
    // Pause stops reporting until resumed, all steps continue to be counted.
    Pause()
}
```

Initially the package was a standalone external dependency, however for the project needs I was asked to include it into the source, so I've copied some (well-tested) code and also made modifications to ensure that the package doesn't provide extra functionality that we don't use. Package provides `ZapReporter` for  the only supported logger that we use.

### Usage examples

The package being used in a currently [pending PR](https://reviewable.io/reviews/CoreumFoundation/coreum/45#-) related to the `corezstress` utility. The utility itself is a CLI app, where without any logging the user doesn't get any idea what the app does at the moment. With a few additional lines of code that setups the pace instance, and ticking it once an event happens, logs will contain info about certain actions pacing (see output examples).

```go
signedTxPace := pace.New("signed tx", 10*time.Second, pace.ZapReporter(log))

			defer func() {
				signedTxPace.Pause()
			}()


					case result := <-results:
						signedTxPace.Step(1)

```

I think the package in this form served me well over years, to add some verbosity into random places in many tools and also as a debugging mechanism to detect stale flows (yes, the tool also reports whether the pacing becomes stale).

Important difference from the other reporting implementations like in [PR #44](https://reviewable.io/reviews/CoreumFoundation/coreum/44#-) is that with a standalone package user is abstracted away from implementing the counter every time with risk of adding concurrency-related and other possible bugs. Also, this drop-in makes code much easier to read.

### Output examples

```
INFO 329923 signed tx in 10s (pace: 32992.300/s)
INFO 333805 signed tx in 10s (pace: 33380.500/s)
INFO 333717 signed tx in 10s (pace: 33371.700/s)
INFO 333716 signed tx in 10s (pace: 33371.600/s)
INFO 334649 signed tx in 10s (pace: 33464.900/s)
INFO 334445 signed tx in 10s (pace: 33444.500/s)
INFO 336089 signed tx in 10s (pace: 33608.900/s)
INFO 333331 signed tx in 10s (pace: 33333.100/s)
INFO 329395 signed tx in 10s (pace: 32939.500/s)
```

```
INFO 3200 sent tx in 10s (pace: 320.000/s)
INFO 3600 sent tx in 10s (pace: 360.000/s)
INFO 3200 sent tx in 10s (pace: 320.000/s)
INFO 3428 sent tx in 10s (pace: 342.800/s)
INFO 2527 sent tx in 10s (pace: 252.700/s)
INFO 2145 sent tx in 10s (pace: 214.500/s)
INFO 2844 sent tx in 10s (pace: 284.400/s)
INFO 2432 sent tx in 10s (pace: 243.200/s)
```


</blockquote></details>

@xlab Thanks for the description. it is nice, and is more complete than what I expected. a shorter description is still acceptable but what you have done is even nicer.

___


<!-- Sent from Reviewable.io -->

2022-06-06 09:06 UTC, miladz68 requested changes
> Reviewed 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 6 unresolved discussions (waiting on @xlab)

___
*[`pkg/pace/pace.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sCPIr3msi42S6kKTz:-N3sCPIr3msi42S6kKU-:b-pcvsya) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L15)):*
> ```Go
> 	Step(n int)
> 	// Pause stops reporting until resumed, all steps continue to be counted.
> 	Pause()
> ```

The original PR where we have the use case (https://reviewable.io/reviews/CoreumFoundation/coreum/44), we only need step and stop function. pause only makes sense when there is resume, but we don't have that use case. 
___
*[`pkg/pace/pace.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sDvtiCxN-mVMjUaMa:-N3sDvtiCxN-mVMjUaMb:b3ixziv) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L41)):*
> ```Go
> }
> 
> func (p *paceImpl) Pause() {
> ```

I think this should be renamed to stop. 
___
*[`pkg/pace/pace.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sEDy0D5v50-0rxH0n:-N3sEDy0D5v50-0rxH0o:b-gtdhz3) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L42)):*
> ```Go
> 
> func (p *paceImpl) Pause() {
> 	p.timer.Stop()
> ```

we should stop reporting loop, and make sure it is stopped. then we will not need mutex, will make the struct and code simpler.


<!-- Sent from Reviewable.io -->

2022-06-06 10:51 UTC, oliverasistemas approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 6 unresolved discussions (waiting on @xlab)



<!-- Sent from Reviewable.io -->

2022-06-06 12:34 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 7 unresolved discussions (waiting on @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t-Ipk4nQt4yEQMG4y:-N3t-Ipk4nQt4yEQMG4z:b-zgttdp) (no related file):*
@xlab Please don't add tags to the repository, pointing to commits which are not in master. Potential users should not be pointed to the code which didn't pass review.

___


<!-- Sent from Reviewable.io -->

2022-06-06 13:37 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t-Ipk4nQt4yEQMG4y:-N3tCDMQAAzGxTB2DjT7:bwzd7x6) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@xlab Please don't add tags to the repository, pointing to commits which are not in master. Potential users should not be pointed to the code which didn't pass review.
</blockquote></details>

The tags are marked as `rc0, ... ,rcN` basically release candidates. Which they are. 
I don't know what users have in mind when trying to use "release candidate" code, but, which tag naming patterns you suggest?

Totally ignoring tags mechanics in git is bad, since `go.mod` allows only commit/tag references. And commits are very easy to confuse. 

___
___
*[`pkg/pace/pace.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sCPIr3msi42S6kKTz:-N3tDv9kDdlEgkD35LMS:b-pmmx6l) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The original PR where we have the use case (https://reviewable.io/reviews/CoreumFoundation/coreum/44), we only need step and stop function. pause only makes sense when there is resume, but we don't have that use case. 
</blockquote></details>

Yep, I agree should be "Stop" then. 
___
*[`pkg/pace/pace.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sEDy0D5v50-0rxH0n:-N3tDeaOE4DPMo-rI9kT:bg45iyn) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should stop reporting loop, and make sure it is stopped. then we will not need mutex, will make the struct and code simpler.
</blockquote></details>

I'll see how this can be optimized, if the meter should be considered dead after stopping.
___
*[`pkg/pace/pace.go` line 79 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t3ifL3EB81qeZ9ew-:-N3tDCyI0Ai4bgjC2orF:b5dhjc6) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L79)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

All the goroutines in the project are started and managed by `parallel` package (https://github.com/CoreumFoundation/coreum-tools/tree/master/pkg/parallel).
Please read README there and have a look at documentation: https://pkg.go.dev/github.com/ridge/parallel
Take a look at example how it is used by benchmark tool: https://github.com/CoreumFoundation/coreum/blob/master/coreznet/pkg/zstress/stress.go#L49
If you have any questions please ping me.

`parallel` is used to run goroutines because it handles errors, panics, synchronization and logging, implemented once for entire project.
So instead of using `go` keyword you should create a function accepting argument of type `parallel.SpawnFn` and this function should be used to spawn the goroutine.
Also you should accept `ctx context.Context` as another argument and exit reporting loop once this context is cancelled, so function `Stop()` and `Pause()` are not needed.
Then you should get logger by calling `log := logger.Get(ctx)` because `ctx` contains correct logger preconfigured by `parallel` (it contains correct logger name).
</blockquote></details>

Let's rename Go to "parallel" too ;)

Go language has enough primitives to manage concurrent code, let's not invent Erlang for the trivial stuff.


<!-- Sent from Reviewable.io -->

2022-06-06 13:42 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 79 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t3ifL3EB81qeZ9ew-:-N3tEL2Q-m9lUiab2SLr:b-c055vn) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L79)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

And I think if the goroutine is controlled by `paceImpl` then mutex would not be needed. This is the point I was trying to make in a previous comment.
</blockquote></details>

@ysv @miladz68 @oliverasistemas 

Guys it's really another deep subject. I tried to dig deeply into whole IoC thing while trying to make a new app. It's a rabbit hole of metaprogramming. So, I just used my oldschool patterns instead, to deliver it quickly and don't have too much meta for a subcommand with few flags.

Let's make another discussion somewhere.

Also, if we enforce this as a rule, I'm fine, but the following must be done before we do that:
1) Full guide on how to create new apps without a lot of boilerplate
2) Strip down unused IoC code, it's really confusing to read
3) Make znet init patterns to be reusable, right now it's all hardcoded for a single use case (of znet app).


<!-- Sent from Reviewable.io -->

2022-06-06 13:43 UTC, miladz68 requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sEDy0D5v50-0rxH0n:-N3tEwcqCltlcgKcSBaE:b-5gsvb) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L42)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I'll see how this can be optimized, if the meter should be considered dead after stopping.
</blockquote></details>

I left a comment below, sorry if my comments are all over the place, but to put it in other words by having more control over the goroutine (preferably with context.Context if it makes sense) then we can do away with mutex.


<!-- Sent from Reviewable.io -->

2022-06-06 13:53 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`pkg/pace/pace.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sDvtiCxN-mVMjUaMa:-N3tBUB8DVoRRea98hXe:bn2216x) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think this should be renamed to stop. 
</blockquote></details>

100% agree because pause is temporary thing so it should logically have sort of continue method
___
*[`pkg/pace/pace.go` line 79 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t3ifL3EB81qeZ9ew-:-N3tEQcV74Dx-0yeeTHK:b-ui9oqg) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L79)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

@ysv @miladz68 @oliverasistemas 

Guys it's really another deep subject. I tried to dig deeply into whole IoC thing while trying to make a new app. It's a rabbit hole of metaprogramming. So, I just used my oldschool patterns instead, to deliver it quickly and don't have too much meta for a subcommand with few flags.

Let's make another discussion somewhere.

Also, if we enforce this as a rule, I'm fine, but the following must be done before we do that:
1) Full guide on how to create new apps without a lot of boilerplate
2) Strip down unused IoC code, it's really confusing to read
3) Make znet init patterns to be reusable, right now it's all hardcoded for a single use case (of znet app).
</blockquote></details>

1. 100% I would  not force to use `parallel` everywhere it is 
2. as for passing context I think it is right thing to be addressed but Stop method is required also because their purpose is different
3. as for fetching logger from ctx I  always try to avoid these type of things it unless it is mandatory. As for me storing of variables in ctx is bad practice similar to global variables but what is more ctx vars are not typed. 
4. As for IoC I agree with Maxim and I also found it challenging to go through all of code and even after spending bunch of hours on it I still don't feel comfortable with codebase


<!-- Sent from Reviewable.io -->

2022-06-06 15:59 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3tRS4P8FYoIaPQ3QHQ:-N3tj7TQ3_m2uGrFNgDk:bjocjni) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is there any specific reason to put it into a separate func ?
</blockquote></details>

In order to have a `defer` that unlocks the mutex. You could place mux unlock directly after p.report, but since `p.report` eventually uses an externally provided callback, it could panic and the mutex will stay locked.

It's important to have mutex unlocks be deferred around arbitrary code. 

I think this problem could be solved by a cascade of parallel/spawn calls, but I don't know how yet (and why).


<!-- Sent from Reviewable.io -->

2022-06-06 16:11 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t-Ipk4nQt4yEQMG4y:-N3tlvd_05VXOVW8JKcI:b4rrzxm) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's not clear how the `replace` directive solves the problem of tagging a particular commit. What `replace` allows me to do extra? Reference files from the disk? But person who checks out the repo doesn't have those files.
</blockquote></details>

Eventually you may use commit ID in `require` directive inside the other go.mod to reference untagged commit, so it works for everyone. But please don't create tags for unreviewed code.

___


<!-- Sent from Reviewable.io -->

2022-06-07 04:51 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t-Ipk4nQt4yEQMG4y:-N3wTpt37TW4etzUTNfh:b-i188rj) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> commit IDs are very easy to confuse.

Especially when something depends on a branch with 3 commits.
</blockquote></details>

As I said, no tags in official repo, pointing to code which hasn't passed reviews please. You have 3 choices:
- `replace` pointing to local copy
- using commit IDs in our repo
- `replace` pointing to your private forked repo, then you may do whatever you like there (this is what @miladz68 does - he forks the repo and then creates PRs to the official ones - I'm not a big fan of this solution but it might work for you in this case)

___


<!-- Sent from Reviewable.io -->

2022-06-07 11:23 UTC, ysv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3ZX9o95Bo7WVjbDdZS:-N3xtDH8CRET7lwBX1mg:b-5d7vzm) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Before even starting reviewing this I will wait for other guys opinion
</blockquote></details>

As for me this package is ok to be merged
It is easy to reuse with a simple interface defined
The implementation source is ~100 lines (+50 for logging) remaining is tests
We could have just done a func in zstress but since we have clean implementation here I would prefer to go with it

___
___
*[`pkg/pace/pace.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3tRS4P8FYoIaPQ3QHQ:-N3xsPwc2v7Q1RjhD9fL:b4398in) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L86)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

In order to have a `defer` that unlocks the mutex. You could place mux unlock directly after p.report, but since `p.report` eventually uses an externally provided callback, it could panic and the mutex will stay locked.

It's important to have mutex unlocks be deferred around arbitrary code. 

I think this problem could be solved by a cascade of parallel/spawn calls, but I don't know how yet (and why).
</blockquote></details>

I see
In such cases I prefer to move this to a separate func then
But current implementation is also ok for me


<!-- Sent from Reviewable.io -->

2022-06-07 11:43 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t-Ipk4nQt4yEQMG4y:-N3xy5T439Ux9poOSNLd:b-sg6vt9) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As I said, no tags in official repo, pointing to code which hasn't passed reviews please. You have 3 choices:
- `replace` pointing to local copy
- using commit IDs in our repo
- `replace` pointing to your private forked repo, then you may do whatever you like there (this is what @miladz68 does - he forks the repo and then creates PRs to the official ones - I'm not a big fan of this solution but it might work for you in this case)
</blockquote></details>

in 1. and 3. cases other person cannot check if PR works or not, because files are inaccessible.

I'll try 2. though

___


<!-- Sent from Reviewable.io -->

2022-06-07 12:07 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sDvtiCxN-mVMjUaMa:-N3y327A-mWHtPJwzWQp:b-f3c7xf) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

100% agree because pause is temporary thing so it should logically have sort of continue method
</blockquote></details>

Now it's stop with full shutdown.
___
*[`pkg/pace/pace.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3sEDy0D5v50-0rxH0n:-N3y2zbK3JNO3YZuGBlf:b382b0c) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I left a comment below, sorry if my comments are all over the place, but to put it in other words by having more control over the goroutine (preferably with context.Context if it makes sense) then we can do away with mutex.
</blockquote></details>

No problem, reasonable. I added it & tests.
___
*[`pkg/pace/pace.go` line 79 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3t3ifL3EB81qeZ9ew-:-N3y2yzN0vxldDpN5Cdu:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L79)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. 100% I would  not force to use `parallel` everywhere it is 
2. as for passing context I think it is right thing to be addressed but Stop method is required also because their purpose is different
3. as for fetching logger from ctx I  always try to avoid these type of things it unless it is mandatory. As for me storing of variables in ctx is bad practice similar to global variables but what is more ctx vars are not typed. 
4. As for IoC I agree with Maxim and I also found it challenging to go through all of code and even after spending bunch of hours on it I still don't feel comfortable with codebase
</blockquote></details>

Done.
___
*[`pkg/pace/pace.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3tRS4P8FYoIaPQ3QHQ:-N3y2y3O8vna7IwZe6Nq:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see
In such cases I prefer to move this to a separate func then
But current implementation is also ok for me
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-07 12:08 UTC, xlab reviewed
> Reviewed 1 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-06-07 18:49 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zBkiG7tiBTBfQfmav:-N3zTgre9Lecj-6Am1-m:byg0sy5) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv @miladz68 
Previously I had a discussion with @xlab regarding using `time.Timer` over simple `<-time.After`. His argument is that there was a guy who created 16 millions timers per second using `time.After`, each leaving for 5 minutes. Obviously that guy killed the garbage collector. @xlab will probably paste a link in the reply.

The thing is that here we don't have this problem. Wouldn't it be better then to just use simple `<-time.After` which is just a one-liner rather than `time.Timer` which must be stored in the struct, started and reseted? Why to care about this additional stuff if you have a fire-and-forget solution?
</blockquote></details>

While referring to "some guy on the internetz" may sound sketchy, the original Go code comment discourages anyone to use `time.After`, it's a cool thing that worked for early projects, but then people started to put it into production and memory begin to be eaten. I didn't want to use `time.After` because it introduces a bad example into the code, some other team member may copy it and put into a hot path.

 I also tried  to simplify time management code there by replacing `time.Timer` with `time.Ticker` in a loop, see this commit https://github.com/CoreumFoundation/coreum-tools/commit/ffd5a40a866ce551d11f408e1573cf9098094035 but Ticker has floating intervals and under heavy GC load the time interval starts to drift, 10s becomes 10.3943409s and so on.

Honestly, I spent on optimising shit out of this package for so much time, I rarely spend so much time on really advanced code.


<!-- Sent from Reviewable.io -->

2022-06-07 18:50 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zBkiG7tiBTBfQfmav:-N3zV2Qe35rRB-l-Dahi:b-4v1dye) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L31)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

While referring to "some guy on the internetz" may sound sketchy, the original Go code comment discourages anyone to use `time.After`, it's a cool thing that worked for early projects, but then people started to put it into production and memory begin to be eaten. I didn't want to use `time.After` because it introduces a bad example into the code, some other team member may copy it and put into a hot path.

 I also tried  to simplify time management code there by replacing `time.Timer` with `time.Ticker` in a loop, see this commit https://github.com/CoreumFoundation/coreum-tools/commit/ffd5a40a866ce551d11f408e1573cf9098094035 but Ticker has floating intervals and under heavy GC load the time interval starts to drift, 10s becomes 10.3943409s and so on.

Honestly, I spent on optimising shit out of this package for so much time, I rarely spend so much time on really advanced code.


</blockquote></details>

![Screenshot 2022-06-07 at 20.42.56.png](https://files.reviewableusercontent.io/images/reviewable/477998/vcw-erUkd8oyhcX5TBytwbj7/Screenshot%202022-06-07%20at%2020.42.56.png)
![Screenshot 2022-06-07 at 20.43.33.png](https://files.reviewableusercontent.io/images/reviewable/477998/zhkGpoDgwDkAiBi8BMTkpj86/Screenshot%202022-06-07%20at%2020.43.33.png)

That being said, it has to be Timer.


<!-- Sent from Reviewable.io -->

2022-06-08 04:01 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N40PRxh2ebHfpvDM09u:-N40PRxh2ebHfpvDM09v:b-obyaq2) (no related file):*
@miladz68 @ysv @xlab 

The more I think about this library the more I'm sure that we should come back to the design board and think about it once again, specifying requirements first. In my opinion it's a reasonable assumption that this package might be used to print more than one metric in the same logical scope. Because we don't have this situation now (and in other unanswered comment I asked about the list of metrics @xlab wants to report), I'm not insisting on supporting the full scenario now, but this code should be ready to add such support by extending the library, not reimplementing it from scratch.

In current state I see three problems related to reporting many metrics:
- each metric starts separate goroutine, its own timer etc. It takes additional resources. I don't care much but if @xlab wants to really discuss performance implications of using `time.After` over `time.Timer` (https://reviewable.io/reviews/CoreumFoundation/coreum-tools/8#-N3zBkiG7tiBTBfQfmav) then this point should be fixed first
- the more important side effect of reporting each metric in its own goroutine is that metrics which are reported together in the source code, won't be printed together in the console. There are (might be - it's reasonable assumption) other goroutines running in parallel, they also log the stuff. Then, logs produced by metrics will be mixed with other logs, which means finding related metrics to compare them will be difficult
- the other side effect of running a goroutine per metric is that chances are great (I guess 100%) that goroutines of the reporters might be scheduled in different order, so the lines in console will appear in a random order each time, forcing me to hunt for the right line I'm interested in at the moment.

So please, let's design this library in the way that it makes our life easier, not harder.

___


<!-- Sent from Reviewable.io -->

2022-06-09 07:21 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/pace/pace_test.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JL0S3aD8nN8-7F5P:-N46JL0S3aD8nN8-7F5Q:bprmd9x) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L21)):*
> ```Go
> 	})
> 
> 	go func() {
> ```

if tested code panics, `go test` will just terminate immediately without running other tests
___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N46JWcd7U3duYCC2pVO:b-5shfp0) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
> ```Go
> 	}()
> 
> 	time.Sleep(50 * time.Millisecond)
> ```

Every time you use `time.Sleep` in this unit test you have no guarantees that the tested code does what you expect. It might happen (and to answer your next question: yes, it really happens) that machine running this test (e.g. in CI) is overloaded causing random failures of testing framework. On the other hand if you set sleep to be high enough to handle 95% of situations and apply this approach in other unit tests then the testing will take much longer.

This is bad approach. If you really want to test this library it should be done without goroutines and library should be written in the way that does not require goroutines to be tested.


<!-- Sent from Reviewable.io -->

2022-06-09 07:22 UTC, wojtek-coreum reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-06-09 10:24 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 21 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zDzB0C85FOLpGdfrj:-N46oEoQ4XIX5_xgZZ-p:bwm8ps1) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 @ysv 
During our discussions on goroutines you agreed that you prefer to manage goroutines manually and you said that it creates a trouble for you if goroutine is hidden somewhere under the hood. This library does exactly that. It hides the goroutine in the constructor of the object.

I completely understand why it is done this way. Because as we discussed managing goroutine is a repeatable task so write this code once. And I know that most of the people do it this way but this fact doesn't mean that this is the right thing.

Basically there are two activities happening here:
- collecting and reporting metric
- managing goroutine

In my opinion those two things should be done separately. This library should expose two functions:
- one for counting: `Step`
- second one for logging: `reportingLoop(ctx context.Context)` which should be made public and renamed to sth like `Run`

Then I should be able to use the library like this:

```
go func() {
    p.Run(ctx) // Run reports status periodically and exits once `ctx` is canceled
}()

for {
    // ...
    p.Step(1)
}
```
</blockquote></details>

Yes that is what I don't like in this solution

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N40PRxh2ebHfpvDM09u:-N46ojyu15N4EOMAoSQT:b-dazmz5) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 @ysv @xlab 

The more I think about this library the more I'm sure that we should come back to the design board and think about it once again, specifying requirements first. In my opinion it's a reasonable assumption that this package might be used to print more than one metric in the same logical scope. Because we don't have this situation now (and in other unanswered comment I asked about the list of metrics @xlab wants to report), I'm not insisting on supporting the full scenario now, but this code should be ready to add such support by extending the library, not reimplementing it from scratch.

In current state I see three problems related to reporting many metrics:
- each metric starts separate goroutine, its own timer etc. It takes additional resources. I don't care much but if @xlab wants to really discuss performance implications of using `time.After` over `time.Timer` (https://reviewable.io/reviews/CoreumFoundation/coreum-tools/8#-N3zBkiG7tiBTBfQfmav) then this point should be fixed first
- the more important side effect of reporting each metric in its own goroutine is that metrics which are reported together in the source code, won't be printed together in the console. There are (might be - it's reasonable assumption) other goroutines running in parallel, they also log the stuff. Then, logs produced by metrics will be mixed with other logs, which means finding related metrics to compare them will be difficult
- the other side effect of running a goroutine per metric is that chances are great (I guess 100%) that goroutines of the reporters might be scheduled in different order, so the lines in console will appear in a random order each time, forcing me to hunt for the right line I'm interested in at the moment.

So please, let's design this library in the way that it makes our life easier, not harder.
</blockquote></details>

Running goroutine per metric doesn't make sense for me also in the way I see it. We should be able to run multiple reporters with multiple metrics reported by each one

___
___
*[`pkg/pace/pace.go` line 72 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zAPGCA1QFa8HUWJw6:-N46qSgY3RMn1a3aBAo-:b-7tdf7d) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L72)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To be compatible with the rest of the software please use `ctx` received as an argument to this function instead of `context.Background()`
</blockquote></details>

agree
___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N46rnwq8jTWK2kJ-YgN:b-2d1c5j) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Every time you use `time.Sleep` in this unit test you have no guarantees that the tested code does what you expect. It might happen (and to answer your next question: yes, it really happens) that machine running this test (e.g. in CI) is overloaded causing random failures of testing framework. On the other hand if you set sleep to be high enough to handle 95% of situations and apply this approach in other unit tests then the testing will take much longer.

This is bad approach. If you really want to test this library it should be done without goroutines and library should be written in the way that does not require goroutines to be tested.
</blockquote></details>

I also don't like to use sleep in tests but if there is no other way to test it it is ok
I believe in this case it should be possible to test without sleep but I would not insist on it much
___
*[`pkg/pace/zap_reporter.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zKHU48bJ5cQkdWDWY:-N46rTm7BbGXTmNNmOnG:b-myq8iw) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What if there are many metrics being reported by the same setup? It would be nice to report them using single log-item instead of flooding the terminal.
Also if there are many metrics reported together it is quite important to group them because if many goroutines log their stuff, then lines from all of them are mixed and it might be hard to find matching values in the stream.
</blockquote></details>

The thing here is that we wanted to log a single metric for new
And I don't see any issue on adding multi-metric logging in this part of code
However in other parts it is more complicated
___
*[`pkg/pace/zap_reporter.go` line 47 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zK0mrAyyFHGY3SOcm:-N46r6JD3meRakmb_UHB:b-rktvht) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is there a reason you use `%s`, `intFmt` and `floatFmt` instead of appropriate `%-something` syntax directly?
</blockquote></details>

It is done to avoid code duplication and looks reasonable for me
___
*[`pkg/pace/zap_reporter.go` line 47 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zKpe9EJFOUILnijmp:-N46rJ7a4KChc9h72Yy_:b-7tdf7d) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you please use structured logging using `zap.Field`s? Logs are there not only to present themselves in the terminal but they are also collected by different tools like elasticsearch, grafana or processed by other software. By using just a simple string you literally kill the possibility of manipulating them (filtering, searching, grouping) [...]

2022-06-09 12:18 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 21 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N40PRxh2ebHfpvDM09u:-N47MQx7-VjUcYhkrOGf:b-58tx83) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Running goroutine per metric doesn't make sense for me also in the way I see it. We should be able to run multiple reporters with multiple metrics reported by each one
</blockquote></details>

To address issues outlined in this comment:

1) multiple goroutines (like 3-4 of extra go routines) will not make any impact on the performance, in a language where goroutines are spawned in millions.

2 -3) log lines are never in perfect order, because you have other logging from other goroutines and any Logger will use buffered logging, this is especially true for cloud environments when logs are collected from multiple sources and ordering is never taken seriously.

___
___
*[`pkg/pace/pace.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3tRS4P8FYoIaPQ3QHQ:-N47NWzE3M0HjCxexVJn:b-6dbjzf) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L86)):*
I tried to resolve the conversation and Reviewable automatically adds "Done."

> current implementation is also ok for me

This is a green light for me.
___
*[`pkg/pace/pace.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zD3V_8vDDXrE1NvnC:-N47NCM1-sxjMmaBKuzT:br6g52a) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't like the idea that object constructor starts the goroutine. Constructor is there to prepare the object. You don't expect that by calling constructor you start some serious job in the background. I consider it to be a design issue. If you want to do it this way there should be a `Start()` method starting the goroutine.
</blockquote></details>

This is a common Go pattern, sometimes it makes sense to make an explicit `Start`, but for this package I wanted to make interface as clean as possible.

Also, it was done this way to match semantics of `time.NewTimer` or `time.NewTicker`, basically you initialize it and it start ticking.
___
*[`pkg/pace/pace_test.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JL0S3aD8nN8-7F5P:-N47NgcH5MbB7-vQoc-r:b-gb5b8p) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

if tested code panics, `go test` will just terminate immediately without running other tests
</blockquote></details>

It's handled by the go testing workflow
___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N47NkZB4oDoloCI2IOG:b-pp65in) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I also don't like to use sleep in tests but if there is no other way to test it it is ok
I believe in this case it should be possible to test without sleep but I would not insist on it much
</blockquote></details>

The code under test has asynchronous nature, I could go miles by scaffolding syncing primitives around, but I decided that using time constrains close to real world that are simplier to use.

This approach should be considered case-by-case of course.
___
*[`pkg/pace/zap_reporter.go` line 47 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zK0mrAyyFHGY3SOcm:-N47OFpz8J2gmEcq2W4u:b-kt3k3e) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It is done to avoid code duplication and looks reasonable for me
</blockquote></details>

Originally it was `floatFmt` in all places, but `intFmt` improves the output clarity. Right now it still makes sense to abstract away the specifics of the number type.
___
*[`pkg/pace/zap_reporter.go` line 47 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zKpe9EJFOUILnijmp:-N47OWQ3DRxPKVLUHhcd:b-lzxjot) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree
</blockquote></details>

I did this on purpose because structured fields in Zap cause the log line to span across multiple lines. With 3 variables there and 2 additional line from the Zap itself, it will be 6 lines of text printed every tick.

However, if you insist I can convert this into structured version easily.


<!-- Sent from Reviewable.io -->

2022-06-09 18:28 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: 4 of 6 files reviewed, 22 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3z99H_-nzMwiueZUK3:-N48hRGuE-uvqa9r8Equ:b-12fkx6) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What fields here are protected by the mutex?
For better readability, could you please divide fieds into two groups:
- those not protected by the mutex
- those protected by the mutex

like this:


```
value    int64
label    string
interval time.Duration

mux *sync.RWMutex
repFn    ReporterFunc
cancelFn func()
timer    *time.Timer
```
?
In the example above I divided the fields randomly. It makes my life easier when it comes to understanding the code.
</blockquote></details>

I've changed the ordering of the fields, also renamed `mux` to `lastTickMux` to signify what it protects now.
___
*[`pkg/pace/pace.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zB5bG5-N4j21IBSTJ:-N48hcCc4t8F6qj0U-6t:bcyng59) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`paceImpl` is returned using pointer so you don't need a pointer to the mutex
</blockquote></details>

It doesn't hurt to have pointer here still.
___
*[`pkg/pace/pace.go` line 30 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zBI1zEehwfRoIYKAL:-N48hhklEm1ItxtOTMWQ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

use `context.CancelFn` as a type for `cancelFn` to clearly indicate its origin and purpose
</blockquote></details>

Done.
___
*[`pkg/pace/pace.go` line 31 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zBkiG7tiBTBfQfmav:-N48hknt2mDEZtW8jCx0:b-h2s7yb) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

To me this discussion seems unproductive. Because I think this is not something to bring on so much back and forth.
</blockquote></details>

I agree, let's move on.
___
*[`pkg/pace/pace.go` line 72 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zAPGCA1QFa8HUWJw6:-N47Os3g6eTaSOsoWXdx:b-8uaecu) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L72)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Added `ctx` param to the `New()` method, now the context has a root.
___
*[`pkg/pace/pace.go` line 63 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N48iAQGCzwwlSXQlkFW:-N48iAQGCzwwlSXQlkFX:b-kz4n1e) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L63)):*
> ```Go
> // All ticks (or steps) are aggregated in timeframes specified using interval.
> // If the reporting function was not provided, ZapReporter will be used as default.
> func New(ctx context.Context, label string, interval time.Duration, reportFn ...ReporterFunc) Pace {
> ```

Made the reportFn optional, can be omitted if you assume that a default-company-wide-standartized-approved reported func shall be used by default.


<!-- Sent from Reviewable.io -->

2022-06-09 18:33 UTC, xlab reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 22 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/zap_reporter.go` line 11 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zKHU48bJ5cQkdWDWY:-N48j79h4diXsTfFdHrd:b-iqqqcd) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

The thing here is that we wanted to log a single metric for new
And I don't see any issue on adding multi-metric logging in this part of code
However in other parts it is more complicated
</blockquote></details>

As has been discussed on the call, the package was never meant as a professional metric collecting package. You don't expect `log.Println` to be able to print 100 log lines at the same time, or `time.NewTimer` to run many timers at once.

This package implements a debugging helper, also some CLI guidance to show some activity in the console and server logs. It's oriented towards INFO/DEBUG logging capabilities, rather than metrics collection agents like Prometheus exporters, etc.
___
*[`pkg/pace/zap_reporter.go` line 19 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zIpPIE_kXCuSpbqej:-N48iboD7MU3ywS-xDzo:bwf9y3v) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/zap_reporter.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please explain what is done inside this `case`
</blockquote></details>

The flow/pace is considered to be stalled and that fact is reported. It helps to avoid situations when you still have 0.00003/s but not stale. This case handles absolute zeroes in a time frame.


<!-- Sent from Reviewable.io -->

2022-06-09 18:37 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 22 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 48 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zHE3uB_eVzV8G5FeQ:-N48jlgp0BRxrA49xywZ:b-b1lm26) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L48)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you please explain the idea behind this `if`? I also don't understand the purpose of `lastTick`.
</blockquote></details>

`lastTick` stores starting point for the current timeframe. Basically the timestamp of the last counter reset.

As for this particular `if`, it rounds up timeframe to `p.interval`, if the difference between them is less than 10ms. This allows to get you round numbers when GC pressure is high or your external triggering function was not accurate 100%, but close enough to `p.interval`.


<!-- Sent from Reviewable.io -->

2022-06-10 06:29 UTC, wojtek-coreum requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 19 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N40PRxh2ebHfpvDM09u:-N4BIEks1-DGQrZjcwLi:bagpdkt) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

To address issues outlined in this comment:

1) multiple goroutines (like 3-4 of extra go routines) will not make any impact on the performance, in a language where goroutines are spawned in millions.

2 -3) log lines are never in perfect order, because you have other logging from other goroutines and any Logger will use buffered logging, this is especially true for cloud environments when logs are collected from multiple sources and ordering is never taken seriously.
</blockquote></details>

I gave more details about points 2 and 3 in other comment in this PR: https://reviewable.io/reviews/CoreumFoundation/coreum-tools/8#-N3zKHU48bJ5cQkdWDWY

Let's continue the discussion there.

___
___
*[`pkg/pace/pace.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3tRS4P8FYoIaPQ3QHQ:-N4BA9rz0am6hce3zise:b6chf5t) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/ffd5a40a866ce551d11f408e1573cf9098094035/pkg/pace/pace.go#L86)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

I tried to resolve the conversation and Reviewable automatically adds "Done."

> current implementation is also ok for me

This is a green light for me.
</blockquote></details>

For me, using inline functions is not an issue but if someone else in the team finds it unclear then I'm for applying this change. @ysv - you made the original comment so it's up to you
___
*[`pkg/pace/pace.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zB5bG5-N4j21IBSTJ:-N4B4w29DkXp0-AJB1Gb:b-zh22mk) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L23)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It doesn't hurt to have pointer here still.
</blockquote></details>

but it just doesn't make sense

@miladz68 
___
*[`pkg/pace/pace.go` line 48 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zHE3uB_eVzV8G5FeQ:-N4B8KAI4DxOyziFqVNd:b-1m0waz) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L48)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

`lastTick` stores starting point for the current timeframe. Basically the timestamp of the last counter reset.

As for this particular `if`, it rounds up timeframe to `p.interval`, if the difference between them is less than 10ms. This allows to get you round numbers when GC pressure is high or your external triggering function was not accurate 100%, but close enough to `p.interval`.
</blockquote></details>

If you want to be as precise as possible in calculations and taking real time between reports instead of just `p.interval` then why do you ignore 10-millisecond shift?  Why not just take the real timeframe as it is returned by `timeframe := time.Since(p.lastTick)` without rounding?
___
*[`pkg/pace/pace.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zD3V_8vDDXrE1NvnC:-N4B9ygA6lj77hnZN24T:bwuag64) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L75)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This is a common Go pattern, sometimes it makes sense to make an explicit `Start`, but for this package I wanted to make interface as clean as possible.

Also, it was done this way to match semantics of `time.NewTimer` or `time.NewTicker`, basically you initialize it and it start ticking.
</blockquote></details>

@miladz68 
___
*[`pkg/pace/pace.go` line 27 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N4B77Vy8XVqscIxZpWN:-N4B77Vz2avNDnocqIVC:b-dl1ey6) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L27)):*
> ```Go
> type paceImpl struct {
> 	lastTickMux *sync.RWMutex
> 	lastTick    time.Time
> ```

`lastTick` is referenced from two methods only `reportingLopp` (running in goroutine) and `report`.  `report` is called only inside `reportingLoop`. It means all the read/write operations on `lastTick` are made by the same goroutine, so you don't need a mutex to protect it.

Moreover `lastTick` could be just a local variable of `reportingLoop` declared before `for` and all the updates could happen inside `reportingLoop`, then `lastTick` could be passed as an argument to `report` method.
___
*[`pkg/pace/pace.go` line 63 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N48iAQGCzwwlSXQlkFW:-N4B9SU49uo3q6dZLKU7:bhkz7gv) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L63)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Made the reportFn optional, can be omitted if you assume that a default-company-wide-standartized-approved reported func shall be used by default.
</blockquote></details>

- using `...` is an antipattern of making an argument optional in go. It suggests  to the caller that it is valid to pass many of them
- I'm for removing it completely

@miladz68 
___
*[`pkg/pace/pace_test.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JL0S3aD8nN8-7F5P:-N4BBHEM8wyCyMIKnK6E:bhmdrax) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L21)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It's handled by the go testing workflow
</blockquote></details>

It's not:

```go
func TestFirst(t *testing.T) {
	done := make(chan struct{})
	go func() {
		panic("panicked")
		close(done)
	}()
	<-done
}

func TestSecond(t *testing.T) {
	assert.Fail(t, "second test failed")
}
```

result of running `go test .`:

```
[wojciech@coreum pkg]$ go test .
panic: panicked

goroutine 20 [running]:
github.com/CoreumFoundation/coreum-tools/pkg.TestFirst.func1()
	/home/wojciech/coreum-tools/pkg/hello_test.go:12 +0x27
created by github.com/CoreumFoundation/coreum-tools/pkg.TestFirst
	/home/wojciech/coreum-tools/pkg/hello_test.go:11 +0x6a
FAIL	github.com/CoreumFoundation/coreum-tools/pkg	0.013s
FAIL
```

`TestSecond` is never executed and it's failure is not reported
___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N4BBt491sUTBhTppXyq:bv17eeo) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

The code under test has asynchronous nature, I could go miles by scaffolding syncing primitives around, but I decided that using time constrains close to real world that are simplier to use.

This approach should be considered case-by-case of course.
</blockquote></details>

IMO If you want to test this code, do it the right way. If the code must be changed to be tested properly - change it. In my opinion the logic in the library could be so simple that it doesn't require testing at all.

More context:
The unit tests are run by CI on every pull request made by all the team members. I really want to avoid situations where someone receives failures unrelated to committed code. In such scenario they must go to CI and inspect resu [...]

2022-06-10 07:26 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zB5bG5-N4j21IBSTJ:-N4BUrBlDi1zDAmuOzz5:b-jru1n0) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but it just doesn't make sense

@miladz68 
</blockquote></details>

I don't think it is necessary but I like to see us stick to a convention and avoid arbitrary styles. I think it makes sense to avoid pointers as much as possible and introduce them as less often as possible. I think if one of them gets the job done, the other one should be avoided.


<!-- Sent from Reviewable.io -->

2022-06-10 07:27 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 63 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N48iAQGCzwwlSXQlkFW:-N4BVYG2CIWY9FrpCPsx:bnbfh3k) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L63)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

- using `...` is an antipattern of making an argument optional in go. It suggests  to the caller that it is valid to pass many of them
- I'm for removing it completely

@miladz68 
</blockquote></details>

I agree with wojtek here. 


<!-- Sent from Reviewable.io -->

2022-06-10 07:42 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 75 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zD3V_8vDDXrE1NvnC:-N4BW61A5A-dwMVxCBVD:b9sv7tp) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 
</blockquote></details>

In our discussion I argued that this goroutine is playing the role of `PrinterController` and is not part of the counter package. for me a separation concerns would be nice


<!-- Sent from Reviewable.io -->

2022-06-10 07:48 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-06-10 07:54 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N4BaUfg-Qu5yNNkaBTb:bpeundh) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO If you want to test this code, do it the right way. If the code must be changed to be tested properly - change it. In my opinion the logic in the library could be so simple that it doesn't require testing at all.

More context:
The unit tests are run by CI on every pull request made by all the team members. I really want to avoid situations where someone receives failures unrelated to committed code. In such scenario they must go to CI and inspect results just to find out that it's unrelated failure caused by overloaded CI server, and then wait until CI runs again. Doing such things to our teammates is really a good practice.

@ysv @miladz68 
</blockquote></details>

testing async code is hard. it is super hard in fact. but writing correct code is hard as well. I agree with yaroslav here I would like to see it done correctly but I would not put too much emphasis on it.


<!-- Sent from Reviewable.io -->

2022-06-10 10:34 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N4CAASy-By-8Z7pmFjQ:bmfwino) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

testing async code is hard. it is super hard in fact. but writing correct code is hard as well. I agree with yaroslav here I would like to see it done correctly but I would not put too much emphasis on it.
</blockquote></details>

Personally if I see a test like this (using unpredictable `Sleep`) I prefer to not have a test at all, especially in this case where tested logic could be simple and once accepted not modified for long time


<!-- Sent from Reviewable.io -->

2022-06-10 13:29 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N3zB5bG5-N4j21IBSTJ:-N4CmTvgEjfGx5FQEiFl:bcm6zp) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L23)):*
> I think it makes sense to avoid pointers as much as possible

any argumentation?
___
*[`pkg/pace/pace.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46kP9ZBfIcEvWdBsEQ:-N4CmXBo9PGxiaiIfV_I:b-fjzb3s) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

with pause and resume function gone. I don't think we need the mutex anymore. 
</blockquote></details>

Mutex locks `lastTick` which still participates in the control loop. Which can become even more important to have, if the package implements an external-controllable ticking like you suggested on the call.
___
*[`pkg/pace/pace_test.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JL0S3aD8nN8-7F5P:-N4Cn7BaACGfhyxsQYhS:b-mx1hl8) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L21)):*
> FAIL

this is the output of the testing workflow, it marks test as failing upon panic.
___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N4Cn_T08jcM1Cvhu38d:bylb6gt) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Personally if I see a test like this (using unpredictable `Sleep`) I prefer to not have a test at all, especially in this case where tested logic could be simple and once accepted not modified for long time
</blockquote></details>

Oh sorry for adding too much tests


<!-- Sent from Reviewable.io -->

2022-06-11 14:05 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace_test.go` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JL0S3aD8nN8-7F5P:-N4I3a1rAoCJjjrTkLf0:b-cygqk2) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L21)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

> FAIL

this is the output of the testing workflow, it marks test as failing upon panic.

</blockquote></details>

The correct output of testing workflow is the list of all failing tests.

@miladz68 
___
*[`pkg/pace/pace_test.go` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N46JWcd7U3duYCC2pVN:-N4I3qmU-30ehiVSp1gi:bhr49qv) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/772a37987684f3d5765a100db8951439f6da52fe/pkg/pace/pace_test.go#L27)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Oh sorry for adding too much tests
</blockquote></details>

@xlab I'm not going to discuss with you this way


<!-- Sent from Reviewable.io -->

2022-06-11 14:29 UTC, wojtek-coreum requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 22 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/pace/pace.go` line 63 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N4I9h_lCxN4jSHzzUuv:-N4I9h_lCxN4jSHzzUuw:bh9rhtl) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L63)):*
> ```Go
> // All ticks (or steps) are aggregated in timeframes specified using interval.
> // If the reporting function was not provided, ZapReporter will be used as default.
> func New(ctx context.Context, label string, interval time.Duration, reportFn ...ReporterFunc) Pace {
> ```

Stop reporting when `ctx` received here is canceled, then you could remove `Stop` method and `cancelFn` completely
___
*[`pkg/pace/pace.go` line 74 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N4I4uBN226Db_7q4i9A:-N4I4uBN226Db_7q4i9B:b-g2gd5w) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L74)):*
> ```Go
> 	}
> 
> 	logger, _ := zap.NewProduction()
> ```

Please use zap logger provided as an argument to `pace` because it might be configured differently than you expect here
___
*[`pkg/pace/pace.go` line 99 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N4I58UJ2A7yK0ae2p9T:-N4I58UJ2A7yK0ae2p9U:bqy595k) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L99)):*
> ```Go
> 			}
> 
> 			p.defaultLogger.With(zap.Error(
> ```

Here and above: you may do it without creating new logger you are not using here:
`p.defaultLogger.Warn("...", zap.Error(...))`
___
*[`pkg/pace/pace.go` line 99 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N4I5xcw2aqrvu1s9R2U:-N4I5xcw2aqrvu1s9R2V:bm13ey9) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace.go#L99)):*
> ```Go
> 			}
> 
> 			p.defaultLogger.With(zap.Error(
> ```

please add `zap.Any("panic", v)` too
___
*[`pkg/pace/pace_test.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8#-N4I8Sot3dabf9hoSxlF:-N4I8Sot3dabf9hoSxlG:b-gkufdw) ([raw file](https://github.com/coreumfoundation/coreum-tools/blob/7d525430bc0702632854065ce1e8295b57b8e16e/pkg/pace/pace_test.go#L18)):*
> ```Go
> 		if stopped {
> 			t.Fatalf("not expected to fire after stop")
> 			t.FailNow()
> ```

1. `testReportingFn` is run in goroutine by `pace`
2. `t.FailNow()`uses `runtime.Goexit` to break the test

That's why documentation of `t.FailNow` says:

```
// FailNow must be called from the goroutine running the
// test or benchmark function, not from other goroutines
// created during the test. Calling FailNow does not stop
// those other goroutines.
```


<!-- Sent from Reviewable.io -->

2022-06-13 05:32 UTC, wojtek-coreum reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum-tools/8)* status: all files reviewed, 22 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-06-13 13:46 UTC, closed without merging